[project]
name = "postgresql-mcp"
version = "0.1.0"
description = "PostgreSQL MCP服务，提供PostgreSQL数据库操作的接口"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.5.0",
    "psycopg2-binary>=2.9.9",
] 